targets:
  $default:
    builders:
      fast_i18n:
        options:
          base_locale: en
          input_directory: assets/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          output_format: single_file
          translate_var: t
