name: silkroad
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.1+6

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_icons:
  file_picker:
  provider: ^6.0.2
  network_info_plus: ^2.3.0
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_svg: ^1.1.5
  platform: ^3.1.0
  mime_type: ^1.0.0
  gallery_saver: ^2.3.2
  shared_preferences: ^2.0.15
  fast_i18n: ^5.12.6
  camel:
  lan_scanner: ^4.0.0
  dart_ping_ios: ^4.0.0
  google_mobile_ads: ^3.0.0
  package_info_plus: ^4.1.0
  http: ^1.1.0

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  mockito:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg_icons/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Klee_One
      fonts:
        - asset: assets/fonts/Klee_One/KleeOne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Klee_One/KleeOne-SemiBold.ttf
          weight: 600

    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
