// Mocks generated by Mockito 5.4.0 from annotations
// in silkroad/test/utils/animated_list_item_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/scheduler.dart' as _i5;
import 'package:flutter/src/widgets/animated_scroll_view.dart' as _i2;
import 'package:flutter/src/widgets/framework.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnimatedList_0 extends _i1.SmartFake implements _i2.AnimatedList {
  _FakeAnimatedList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeBuildContext_1 extends _i1.SmartFake implements _i4.BuildContext {
  _FakeBuildContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_3 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeTicker_4 extends _i1.SmartFake implements _i5.Ticker {
  _FakeTicker_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({bool? debugIncludeStack = false}) => super.toString();
}

/// A class which mocks [LabeledGlobalKey].
///
/// See the documentation for Mockito's code generation for more information.
class MockLabeledGlobalKey<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.Mock implements _i4.LabeledGlobalKey<T> {
  MockLabeledGlobalKey() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AnimatedListState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimatedListState extends _i1.Mock implements _i2.AnimatedListState {
  MockAnimatedListState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnimatedList get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeAnimatedList_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.AnimatedList);
  @override
  _i4.BuildContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeBuildContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i4.BuildContext);
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);
  @override
  _i4.Widget build(_i4.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #build,
          [context],
        ),
        returnValue: _FakeWidget_2(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
      ) as _i4.Widget);
  @override
  void insertItem(
    int? index, {
    Duration? duration = const Duration(milliseconds: 300),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #insertItem,
          [index],
          {#duration: duration},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void insertAllItems(
    int? index,
    int? length, {
    Duration? duration = const Duration(milliseconds: 300),
    bool? isAsync = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #insertAllItems,
          [
            index,
            length,
          ],
          {
            #duration: duration,
            #isAsync: isAsync,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeItem(
    int? index,
    _i2.AnimatedRemovedItemBuilder? builder, {
    Duration? duration = const Duration(milliseconds: 300),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [
            index,
            builder,
          ],
          {#duration: duration},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeAllItems(
    _i2.AnimatedRemovedItemBuilder? builder, {
    Duration? duration = const Duration(milliseconds: 300),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeAllItems,
          [builder],
          {#duration: duration},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void initState() => super.noSuchMethod(
        Invocation.method(
          #initState,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didUpdateWidget(_i2.AnimatedList? oldWidget) => super.noSuchMethod(
        Invocation.method(
          #didUpdateWidget,
          [oldWidget],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void reassemble() => super.noSuchMethod(
        Invocation.method(
          #reassemble,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setState(_i6.VoidCallback? fn) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [fn],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeDependencies() => super.noSuchMethod(
        Invocation.method(
          #didChangeDependencies,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void debugFillProperties(_i3.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );
  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i3.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i3.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_3(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i3.DiagnosticsNode);
  @override
  _i5.Ticker createTicker(_i5.TickerCallback? onTick) => (super.noSuchMethod(
        Invocation.method(
          #createTicker,
          [onTick],
        ),
        returnValue: _FakeTicker_4(
          this,
          Invocation.method(
            #createTicker,
            [onTick],
          ),
        ),
      ) as _i5.Ticker);
}
